server:
  port: 8090
  
#指定mybatis 配置文件位置
mybatis:
  config-location: classpath:mybatis-config.xml
  
spring:
  shardingsphere:
    datasource:
      names:
        master
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/masterdb?characterEncoding=utf-8
        username: root
        password: root
    sharding:      
      tables:
        tab_user: 
          actual-data-nodes: master.tab_user$->{0..2}
          table-strategy: 
            inline:
              sharding-column: id
              algorithm-expression: tab_user$->{id % 3}
    defaultDataSourceName: master
    props:
      # 开启SQL显示，默认false
      sql:
        show: true            
  
  
  
  
  
  
  