server:
  port: 8090
  
#指定mybatis 配置文件位置
mybatis:
  config-location: classpath:mybatis-config.xml
  
spring:
  shardingsphere:
    datasource:
      names:
        ds0,ds1
      # 主数据源
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds0?characterEncoding=utf-8
        username: root
        password: root
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds1?characterEncoding=utf-8
        username: root
        password: root
    sharding:      
      tables:
        tab_user: 
          actual-data-nodes: ds$->{0..1}.tab_user$->{0..1}
          database-strategy:
            inline:
              sharding-column: age
              algorithm-expression: ds$->{age % 2}
          table-strategy: 
            inline:
              sharding-column: id
              algorithm-expression: tab_user$->{id % 3}
    props:
      # 开启SQL显示，默认false
      sql:
        show: true            
  
